<!DOCTYPE html>
<html lang="ja-JP">
	<head>
		<meta charset="utf-8">
		<meta name="author" content="reinforchu">
		<meta name="description" content="pic.reinforce.tv">
		<meta name="keywords" content="リインフォース,reinforchu,twitter">
		<meta name="robots" content="index,follow,noarchive">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>pic.reinforce.tv</title>
		<link rel="shortcut icon" href="http://xn--eckk2c4f8d7b7c.jp/schwertkreuz.ico" type="image/vnd.microsoft.icon">
		<link href="http://file.reinforce.tv/bootstrap/v2.1.1/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="./css/common.css" type="text/css">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<style type="text/css">
			body {
				color: #072766;
				background-color: #ffffff;
				background: transparent url('http://xn--eckk2c4f8d7b7c.jp/files/nanoha/bg2w.jpg') no-repeat;
			}
			.summary { padding-left: 0px; }
		</style>
		<link href="http://file.reinforce.tv/bootstrap/v2.1.1/css/bootstrap-responsive.min.css" rel="stylesheet">
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top BarBoxShadow">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="http://pic.reinforce.tv/">pic.reinforce.tv</a>
					</div>
				</div>
			</div>
		</div>
		<div class="hero-unit summary anzu" style="position: relative; top:-15px; left: auto; text-align: center;">
			<h2>写真をアップロードできます！</h2>
			<p>※twitterアカウントが必要です。</p>
			<a href="./?authenticate=1"><img src="http://reinforce-zwei.net/love/sign-in-with-twitter_0_320.png" width="320" height="41" border="0" title="Sign in with twitter"></a>
		</div>

	</body>
</html>